version: "3.1"

networks:
  help:
    driver: "bridge"

services:
  init-redis:
    build: ./init
    container_name: "init-redis"
    restart: "no"
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm
      - /sys/kernel/mm:/mnt/mm
    networks:
      - help
  myredis:
    image: "redis"
    restart: always
    container_name: "myredis"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - help
    depends_on:
      - init-redis
